export default [
  {
    id: 1,
    avatar: "avatar-mark-webber.webp",
    name: "Mark Webber",
    firstMessage: "reacted to your recent",
    secondMessage: "My first tournament today",
    online: true,
    recent: "1m ago",
  },
  {
    id: 2,
    avatar: "./avatar-angela-gray.webp",
    name: "Angela Gray",
    firstMessage: "followed you",
    online: true,
    recent: "5m ago",
  },
  {
    id: 3,
    avatar: "./avatar-jacob-Thompson.webp",
    name: "Jacob Thompson",
    firstMessage: "has joined your group",
    secondMessage: "Chess Club",
    online: true,
    recent: "1 day ago",
  },
  {
    id: 4,
    avatar: "./avatar-rizky-hasanuddin.webp",
    name: "Rizky Hasanuddin",
    firstMessage: "sent you a private message",
    online: false,
    recent: "5 days ago",
  },
  {
    id: 5,
    avatar: "./avatar-kimberly-smith.webp",
    name: "Kimberly Smith",
    firstMessage: "commented on your picture",
    online: false,
    recent: "1 week ago",
  },
  {
    id: 6,
    avatar: "./avatar-nathan-peterson.webp",
    name: "Nathan Peterson",
    firstMessage: "reacted to your recent post",
    secondMessage: "5 end-game strategies to increase your win rate",
    online: false,
    recent: "2 weeks ago",
  },
  {
    id: 7,
    avatar: "./avatar-anna-kim.webp",
    name: "Anna Kim",
    firstMessage: "left the group",
    online: false,
    recent: "2 weeks ago",
  },
];
